name: Server Docker Image CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: yarn install --frozen-lockfile
      - run: yarn prisma:generate
      - run: yarn build
      - run: yarn test

  # build-docker-image:
  #   needs: check
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   env:
  #     dockerImage: europe-west1-docker.pkg.dev/personalweb-279207/stefanpuia/anysub
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Docker Login
  #       env:
  #         DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
  #       run: echo $DOCKER_PASSWORD | docker login -u _json_key --password-stdin https://europe-west1-docker.pkg.dev

  #     - name: Docker Build
  #       run: DOCKER_BUILDKIT=1 docker build -f ./Dockerfile -t "${{ env.dockerImage }}:build-${{ github.run_id }}" -t "${{ env.dockerImage }}:latest" .

  #     - name: Docker Push
  #       run: docker image push --all-tags "${{ env.dockerImage }}"
