name: Worker Docker Image CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - worker
  push:
    branches:
      - main
      - develop
    paths:
      - worker

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      working-directory: ./worker
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: yarn install --frozen-lockfile
        working-directory: ${{env.working-directory}}
      - run: yarn test
        working-directory: ${{env.working-directory}}
      - run: yarn build
        working-directory: ${{env.working-directory}}
